### PR TITLE
Mark FMUs that are not compliant with the FMI standard

### PR DESCRIPTION
**Pull request by lochel**
This is a continuation of #120.

I run the win64 FMUs with OMSimulator and received some complaints that certain FMUs are not strictly compliant with the FMI standard. @chrbertsch, @KarlWernersson and others, please confirm or reject the findings.

_This time, I haven't included reasons for all the test cases, as it was rejected earlier on by @t-sommer (for reference: https://github.com/modelica/fmi-cross-check/pull/120#pullrequestreview-703574741, https://github.com/modelica/fmi-cross-check/issues/121#issuecomment-877773418)._

### CODE REVIEW

**Comment by t-sommer** [comment]
> This time, I haven't included reasons for all the test cases

Can you please re-add the reasons (or the copy it into the comment, if it's the same for all) to make the PR easier to review?

**Comment by lochel** [comment]
_I would like to reiterate that it would indeed be very beneficial to give at least one reason for each invalid FMU. I don't know why the discussion on this issue was cut short: #121._

Anyway, all the examples in this pull request provides incomplete information on derivatives and/or initial unknowns in the model structure section. It would be very much appreciated if someone could approve or reject the findings.

**Comment by casella** [comment]
I can try to be more specific, based on what I understood from @lochel. The FMI specification 2.0.2, Section 2.2.8, states

> The structure of the model is defined in element “ ModelStructure ”. <...> The required part defines an ordering of the outputs and of the (exposed) derivatives, and defines the unknowns that are available during Initialization. <...> A ModelExchange FMU **must expose all derivatives of its continuous-time states in element <Derivatives>**

This information is essential for tools that simulate interconnected FMUs, e.g. using the SSP standard, to figure out the right order of execution of FMUs.

The reported FMUs expose all the derivatives in the ModelVariables structure (with the derivative attribute), but only expose a partial subset of them in the ModelStructure element of the XML file. This is not conforming to the standard as reported above and breaks the algorithms that rely on this mandatory information to guide the execution of models built by interconnected FMUs.

**Comment by casella** [comment]
For the record, this issue has consequences in real life. 

We are trying to simulate complex system models made by connecting FMUs generated by Dymola. The lack of such information, which should be there according to the standard, is causing lots of problems with the simulation of those systems. Those problems wouldn't be there in the first place if those FMUs were actually compliant with the standard.

The whole point of open standards is that people should be able to rely on them to build their own software, whithout caring which software actually produced the FMUs. If those standards are not strictly enforced, the whole concept comes crashing down.

**Comment by t-sommer** [comment]
@KarlWernersson, can you comment on this?

**Review by t-sommer — CHANGES_REQUESTED** [review]
Waiting for feedback from @KarlWernersson.

**Comment by pmai** [comment]
> I can try to be more specific, based on what I understood from @lochel. The FMI specification 2.0.2, Section 2.2.8, states
> 
> > The structure of the model is defined in element “ ModelStructure ”. <...> The required part defines an ordering of the outputs and of the (exposed) derivatives, and defines the unknowns that are available during Initialization. <...> A ModelExchange FMU **must expose all derivatives of its continuous-time states in element Derivatives**

First of all it is still not clear to me how this maps to the individual FMUs that are marked as non-compliant in this PR:

- The first FMU is a **Co-Simulation** FMU: fmus/2.0/cs/win64/CATIA/R2015x/Rectifier/notCompliantWithLatestRules
  
  Looking at that FMU, all output variables are listed in ModelStructure Outputs, as required. There is no requirement for CS FMUs to list derivatives in the model structure at all, so the partial listing of derivatives in the model structure is certainly valid.

  So is there some other reason this FMU is listed?

  The same seems to be true of the next CS FMU on the list; since I don't plan to check all of them by hand, can you be more specific why the CS FMUs are on the list and/or what additional problems you are seeing there?

- If we look at the Model Exchange FMUs, again for the Rectifier FMU, all outputs are listed in Unknowns, so not a problem, I would think. 

  However the objection seems to be that not all Scalar Variables marked as derivatives in the ModelVariables are listed in the ModelStructure Derivatives section. Yet I do not see how this is a priori a violation of the standard: The standard requires all derivatives _of its continuous-time **states**_ to be listed in the Derivatives section. Certainly not all continuous (output) variables are continuous-time **states**, and hence not all derivatives are derivatives of continuous-time states.

  Rather the reverse is true: All derivatives listed in the Derivatives section are derivatives of continuous-time states (by being listed there), and hence that is the way (and the only way) to identify continuous-time states. In that sense the sentence in the standard quoted by you is not a prescription of consistency between ScalarVariables and ModelStructure, but rather a definitorial statement.

  So at a purely syntacic level I can find no fault with this FMU either. It might be that the FMU should have more states than it has, but without looking into the model it was derived from, I don't want to judge.

> The reported FMUs expose all the derivatives in the ModelVariables structure (with the derivative attribute), but only expose a partial subset of them in the ModelStructure element of the XML file. This is not conforming to the standard as reported above and breaks the algorithms that rely on this mandatory information to guide the execution of models built by interconnected FMUs.

As stated above, I think this is a misunderstanding of the standard. All entries in the ModelStructure Derivatives section must be ScalarVariables with attribute derivative; the reverse is not true; see e.g. page 57 on the derivative attribute of ScalarVariables:

> If present, this variable is the derivative of variable with ScalarVariable index 
"derivative". [For example, if there are 10 ScalarVariables and derivative = 3 for 
ScalarVariable 8, then ScalarVariable 8 is the derivative of ScalarVariable 3 with 
respect to the independent variable (usually time). This information might be 
especially used if an input or an output is the derivative of another input or output, 
or to define the states.]
The state derivatives of an FMU are listed under element 
`<ModelStructure><Derivatives>`. All ScalarVariables listed in this element 
must have attribute derivative (in order that the continuous-time states are 
uniquely defined).

In any case maybe I am missing something in those FMUs that is objectionable, I have not carefully reviewed every facet of them, but with the given information I am at a loss in locating those problems, so I think further specific information is needed.

**Comment by lochel** [comment]
@pmai thanks, I will go through your comments carefully next week and double check with the issues I was facing :+1:

**Comment by lochel** [comment]
@pmai thank again for your constructive comment. I agree with your point of view; I simply misinterpreted the standard. That is certainly good news and therewith I am closing this issue.

**Pull request closed without merging**
