### PR TITLE
Results CosiMate 2020.01 FMI 1.0 and 2.0 (win32 and win64)

### PR DESCRIPTION
**Pull request by matthieujude1**
add results cosimulation CosiMate 2020.01 FMI 1.0 and 2.0

### CODE REVIEW

**Comment by matthieujude1** [comment]
Dear @t-sommer,
Could you check our co-simulation results FMI 1.0 and 2.0 using CosiMate tool please ?
Best regards,
Matthieu

**Comment by t-sommer** [comment]
@matthieujude1, did you forget to add the `passed` files? Otherwise this PR will have no effect on the Cross-Check results.

**Comment by matthieujude1** [comment]
@t-sommer sorry for it, I've read passed / failed / rejected file was optional. I'll add it.

**Comment by matthieujude1** [comment]
@t-sommer normally I've added all necessaries files. I see "Your tests failed on CircleCI" 
Do I have to do it on CircleCI ?

**Comment by matthieujude1** [comment]
@t-sommer Many thanks for your help.

**Pull request merged**
