### PR TITLE
Exclude FMUs with illegal variable names

### PR DESCRIPTION
**Pull request by t-sommer**
for naming convention "structured"

### CODE REVIEW

**Comment by t-sommer** [comment]
@CThuleHansen, @nickbattle, can you take a look at this? The validation results should be in line with [your results](https://github.com/INTO-CPS-Association/FMI2-VDM-Model/releases/download/0.0.2-1/fmuCheck.results).

**Comment by nickbattle** [comment]
Using the latest VDMCheck (and the latest fmuCheck agrees), 123 files from the Cross-Check repository have invalid names. The list of FMUs affected is attached. There are actually only three systematic errors:

* Some names use round brackets rather than square ones
* Some names add a space after the comma in comma-separated bracketed indexes
* Some names include a "/" character.

The set of files in error is 
[invalidNames.txt](https://github.com/modelica/fmi-cross-check/files/3717992/invalidNames.txt)

The list of structured name errors is 
[invalidVarNames.txt](https://github.com/modelica/fmi-cross-check/files/3718007/invalidVarNames.txt)

**Comment by nickbattle** [comment]
I should also mention that 16 FMUs have names which are of the form "der(...)", which are syntactically valid, but whose variables are **not** marked as derivatives:

```
./me/win64/SystemModeler/5.0/CoupledClutches/CoupledClutches.fmu
./me/win32/SystemModeler/5.0/CoupledClutches/CoupledClutches.fmu
./me/win32/JModelica.org/1.15/CauerLowPassAnalog/CauerLowPassAnalog.fmu
./me/win32/JModelica.org/1.15/PID_Controller/PID_Controller.fmu
./me/win32/JModelica.org/1.15/CoupledClutches/CoupledClutches.fmu
./me/darwin64/SystemModeler/5.0/CoupledClutches/CoupledClutches.fmu
./me/linux64/SystemModeler/5.0/CoupledClutches/CoupledClutches.fmu
./me/linux64/JModelica.org/1.15/CauerLowPassAnalog/CauerLowPassAnalog.fmu
./me/linux64/JModelica.org/1.15/PID_Controller/PID_Controller.fmu
./me/linux64/JModelica.org/1.15/CoupledClutches/CoupledClutches.fmu
./cs/win32/JModelica.org/1.15/CauerLowPassAnalog/CauerLowPassAnalog.fmu
./cs/win32/JModelica.org/1.15/PID_Controller/PID_Controller.fmu
./cs/win32/JModelica.org/1.15/CoupledClutches/CoupledClutches.fmu
./cs/linux64/JModelica.org/1.15/CauerLowPassAnalog/CauerLowPassAnalog.fmu
./cs/linux64/JModelica.org/1.15/PID_Controller/PID_Controller.fmu
./cs/linux64/JModelica.org/1.15/CoupledClutches/CoupledClutches.fmu
```
For example, from ./me/win64/SystemModeler/5.0/CoupledClutches/CoupledClutches.fmu:
```
    <ScalarVariable name="der(J3.phi)" valueReference="121" description="Derivative of phi" causality="local" variability="continuous" initial="calculated">
      <Real declaredType="Modelica.SIunits.Angle" unit="rad/s"/>
    </ScalarVariable>
```
Whereas this, from the same FMU, is correct:
```
    <ScalarVariable name="der(clutch1.phi_rel)" valueReference="8" description="Derivative of phi_rel" causality="local" variability="continuous" initial="calculated">
      <Real unit="rad/s" derivative="4"/>
    </ScalarVariable>
```
[invalidDerivatives.txt](https://github.com/modelica/fmi-cross-check/files/3718144/invalidDerivatives.txt)

**Comment by nickbattle** [comment]
@t-sommer  Is the intention to use this branch to correct the structured name errors? I see that the directories with errors have a new empty file called "notCompliantWithLatestRules", but the FMUs themselves have not been changed yet.

**Comment by t-sommer** [comment]
> @t-sommer Is the intention to use this branch to correct the structured name errors?

No. FMUs may only be updated, if they're exported with the same version of the tool that was used originally (e.g. if someone forgot to disable the license check).

> I see that the directories with errors have a new empty file called "notCompliantWithLatestRules", but the FMUs themselves have not been changed yet.

We keep the illegal FMUs. Other people might depend on them (e.g. for their CI).

**Comment by t-sommer** [comment]
> I should also mention that 16 FMUs have names which are of the form "der(...)", which are syntactically valid, but whose variables are not marked as derivatives:

Thanks for the hint! I'll prepare a separate PR to sort them out.

**Comment by chrbertsch** [comment]
Will tools that until now have reported to successully simulate these FMUs keep their green button, if the minimum number depends on these ressults? Will they count in the numbers?

**Comment by t-sommer** [comment]
> Will they count in the numbers?

Results for illegal FMUs don't count. There are enough valid FMUs to get a green button.

**Comment by chrbertsch** [comment]
> > Will they count in the numbers?
> 
> Results for illegal FMUs don't count. There are enough valid FMUs to get a green button.

Is there a mechanism to inform tool vendors about this?
Perhaps we should inform tool vendors in a general email  about this policy and recommend to them not to rely only on the minimal submissions of results for three tools ...

Regarding the variable names including 'der(..)' without declaring them as derivatives: I agree that this is a bad practice, but are they really illegal? As this affects jmodelica and SystemModeler FMUs:  @hubertus65 and @otronarp or other Modelon and Wolfram colleagues: could you please comment

@apillekeit: any comment from your side on this PR? We shortly discussed this in Lund.

**Comment by andreas-junghanns** [comment]
I think the standard is not strict (enough) on that naming. Or did I miss this?
While this is confusing and bad practise, it is not strictly illegal according to 2.0 and 2.0.1.

Maybe we should be more explicit in 3.0?

**Comment by t-sommer** [comment]
> I think the standard is not strict (enough) on that naming.

Citing from the FMI 2.0 spec:

A derivative of a variable is defined with “der(name)” for the first time derivative and “der(name,N)” for the N-th derivative. (2.2.9)

The state derivatives of an FMU are listed under element <ModelStructure><Derivatives>. All ScalarVariables listed in this element must have attribute derivative (in order that the continuous-time states are uniquely defined). (p. 54)

Derivatives: Ordered list of all state derivatives, in other words a list of ScalarVariable indices where every corresponding ScalarVariable must be a state derivative. (p. 58)

**Comment by andreas-junghanns** [comment]
> > I think the standard is not strict (enough) on that naming.
> Citing from the FMI 2.0 spec:
> A derivative of a variable is defined with “der(name)” for the first time derivative and “der(name,N)” for the N-th derivative. (2.2.9)
This is only for "variableNamingConvention = "structured"" - all others leave this undefined.

**Comment by t-sommer** [comment]
superseded by 625f9f083af9a7c5d75c426c0a40a2976f116bd4

**Comment by t-sommer** [comment]
> This is only for "variableNamingConvention = "structured"" - all others leave this undefined.

The rules regarding `der(...)` are only enforced for `variableNamingConvention="structured"`.

**Comment by t-sommer** [comment]
> Is there a mechanism to inform tool vendors about this?

Yes: whatch the repos. The process is fully transparent.

**Comment by otronarp** [comment]
We only mark the state derivatives with the `"derivative"` attribute, the `der(...)` variables you see without that are dummy derivatives introduced by index reduction.

So none of the these two cited parts apply to those variables (since the aren't state derivatives).

> The state derivatives of an FMU are listed under element . All ScalarVariables listed in this element must have attribute derivative (in order that the continuous-time states are uniquely defined). (p. 54)

> Derivatives: Ordered list of all state derivatives, in other words a list of ScalarVariable indices where every corresponding ScalarVariable must be a state derivative. (p. 58)

**Comment by t-sommer** [comment]
> So none of the these two cited parts apply to those variables (since the aren't state derivatives).

Should I remove the `notCompliantWithLatestRules` file for these 12 FMUs?

**Comment by nickbattle** [comment]
Currently, VDMCheck only applies this "der" check for structured names, but it does also currently state that all "der" names should be Real and derivatives. This may be too strict, but I'm glad that our attempts to formalise the standard are shaking out these ambiguities. When this discussion has settled, I'll tweak the tool:
```
md.attributes.variableNamingConvention = <structured> =>
...
	-- @OnFail("2.2.9 Structured name %s invalid at line %s", sv.name, sv.location)
	( isValidStructuredName(sv.name) ),
	
	-- @OnFail("2.2.9 Name %s is not a derivative at line %s", sv.name, sv.location)
	( sv.name(1, ..., 4) = "der(" =>
		is_Real(sv.variable) and sv.variable.derivative <> nil )
```

**Comment by otronarp** [comment]
Since there isn't an equivalence between having a `der(..)` name and the `"derivative"` attribute set to true (a variable named `a` can also be a derivative).  So in general you cannot use the name to know if it's a derivative or not. Therefore it's very strict check in my opinion.

On the other hand, I'm all for strict checking so I'm fine with either way.

**Comment by nickbattle** [comment]
I'm trying to produce a formal specification of the standard, with little background experience, guided only by what the standard says and what example FMUs actually do. So it's difficult for me to decide what is a hard and fast rule, and what is not.

That said, the "der(...)" naming is explicitly stated in the grammar, so it ought to have a special meaning? There is a footnote that says that the grammar is the same as Modelica v3.2, though that doesn't mean that the semantics are the same.

I note that some FMUs have bracketed names like "msimder(J1.phi)", which are derivatives and have a description field that uses "der" syntax...

```
    <ScalarVariable
      name           = "msimder(J1.phi)"
      valueReference = "59"
      description    = "der(J1.phi)" >
      <Real 
        derivative = "2"/>
    </ScalarVariable>
```
So perhaps we should clarify the meaning of "der" names, the derivative flag, and the ModelStructure/Derivatives list?

**Comment by chrbertsch** [comment]
> Should I remove the `notCompliantWithLatestRules` file for these 12 FMUs?

In my opinion, yes.

**Comment by nickbattle** [comment]
@chrbertsch I can soften the checks, in that case. So a "der(...)" name is still special, in the sense that it appears in the grammar and is the only round-bracketed name that is allowed, but it need not be for a variable labelled as "derivative". But presumably it must still be a Real and "continuous"?

**Comment by nickbattle** [comment]
> But presumably it must still be a Real and "continuous"?

There are lots of examples of "tunable" and "constant" der names. But they do appear to all be Real. So perhaps that is the weakest precondition?

**Comment by otronarp** [comment]
> > But presumably it must still be a Real and "continuous"?
> 
> There are lots of examples of "tunable" and "constant" der names. But they do appear to all be Real. So perhaps that is the weakest precondition?

There is nothing wrong with a constant derivative, a good tool can deduce that a derivative is constant and therefore mark it as constant.

**Comment by t-sommer** [comment]
> There are lots of examples of "tunable" and "constant" der names. But they do appear to all be Real. So perhaps that is the weakest precondition?

@nickbattle, can you formulate a rule, so we can add it to the validation?

**Comment by nickbattle** [comment]
> @nickbattle, can you formulate a rule, so we can add it to the validation?

@t-sommer Do you mean the VDMCheck validation, or a different one? I've already updated the model, so in VDM-SL the check is now:
```
md.attributes.variableNamingConvention = <structured> =>
...
	-- @OnFail("2.2.9 Structured name %s invalid at line %s", sv.name, sv.location)
	( isValidStructuredName(sv.name) ),

	-- @OnFail("2.2.9 Name %s is not Real at line %s", sv.name, sv.location)
	( sv.name(1, ..., 4) = "der(" => is_Real(sv.variable) )
```
And you'll be pleased to know that there are no FMUs that fail this new check clause.

**Pull request closed without merging**
