### PR TITLE
Submit MapleSim 2018 FMUs 1.0CS, 2.0CS/ME

### PR DESCRIPTION
**Pull request by Maplesoft-fmigroup**

### CODE REVIEW

**Comment by Maplesoft-fmigroup** [comment]
Leaving out FMUs 1.0ME  since the circleci check fails for these with error:
ERROR (line 15, column 0): Element 'fmiModelDescription', attribute 
'version': '' is not a valid value of the atomic type 'xs:decimal'.
For all MapleSim FMU's we have left version="" (empty string). The only ones that fail with the error above are the 1.0ME FMUs. Should this be filed as a circleci checker bug? Thank you.

**Comment by t-sommer** [comment]
According to the schema (fmiModelDescription.xsd) the version must be equal to "1.0" (not empty):

`<xs:attribute name="fmiVersion" type="xs:normalizedString" use="required" fixed="1.0"/>`

**Comment by Maplesoft-fmigroup** [comment]
The 'fmiVersion' attribute is different from the 'version' attribute. For 'fmiVersion', we have fmiVersion = "1.0". For 'version', we have version = "".
For example, see the following MapleSim 1.0ME FMU for the ControlledTemperature model:
`<fmiModelDescription`
`  fmiVersion               = "1.0"`
`  modelName                = "ControlledTemperature"`
`  modelIdentifier          = "ControlledTemperature"`
`  guid                     = "{9a59150b-7af3-05bd-538e-4aaa96cb573a}"`
`  description              = "Model ControlledTemperature"`
`  author                   = ""`
`  version                  = ""`
`  generationTool           = "MapleSim (1357016/1357326/1357326)"`
`  generationDateAndTime    = "2018-10-25T19:51:11Z"`
`  variableNamingConvention = "structured"`
`  numberOfContinuousStates = "1"`
`  numberOfEventIndicators  = "0">`
The error says:
`ERROR (line 15, column 0): Element 'fmiModelDescription', attribute 'version': '' is not a valid value of the atomic type 'xs:decimal'.`

**Comment by t-sommer** [comment]
Sorry, my bad. But an empty string is not a valid decimal:

`<xs:attribute name="version" type="xs:decimal">`

**Comment by t-sommer** [comment]
The attribute "version" is optional so why do you want to add it if it's empty?

**Comment by Maplesoft-fmigroup** [comment]
Regarding the 'version' type for FMI 1.0 ME and CS, please refer to issues #36, #47, and #346.
Also, from the xsd schemata
- FMI for ME v1.0.1: `<xs:attribute name="version" type="xs:normalizedString">`
- FMI for CS v1.0.1: `<xs:attribute name="version" type="xs:decimal">`
- FMI for ME and CS v2.0: `<xs:attribute name="version" type="xs:normalizedString">`

Some comments from the above tickets are quoted below. 
> **Comment by otter on 7 Apr 2011 08:25 UTC**
> I did not notice this. It seems:
> 
> * In FMI 1.0 for model exchange, "version" is a string.
> * In FMI 1.0 for co-simulation, "version" is a decimal number.
> 
> So, there is already an inconsistency in FMI 1.0.
> 
> Since the basis of FMI 2.0 was the Co-Simulation xml schema, this change was (unintentionally included). I vaguely remember that there was previously a discussion, probably because a decimal number allows to decide whether a version is newer as another one, whether this is not possible for a string.

> **Comment by otter on 12 Apr 2011 12:59 UTC**
> Decision at FMI-Meeting in April 2011:
> 
> Accept proposal (use String for FMU version)

> **Comment by mfriedrich on 9 Sep 2015 16:29 UTC**
> The FMI 1.0 for Model Exchange spec (PDF) defines version as xs:normalizedString.
> The FMI 1.0 for Co-Simulation spec (PDF) does not define the type of version.
> The FMI 2.0 spec (PDF) defines version as xs:normalizedString.
> 
> The FMI 1.0 for Model Exchange XML schema (xsd file) defines version as xs:normalizedString.
> The FMI 1.0 for Co-Simulation XML schema (xsd file) defines version as xs:decimal.
> The FMI 2.0 XML schema (xsd file) defines version as xs:normalizedString.
> 
> Hence, their is no flaw, neither between the spec (PDF) and the XML schema (xsd file) or in the pre-commit hook.
> 
> However, I fully agree that this is inconsistent in FMI 1.0.

**Comment by t-sommer** [comment]
I wasn't aware of this inconsistency. The version type [is now relaxed](https://github.com/CATIA-Systems/FMPy/commit/3f1061c0120429c694fb80ea094dcdb34e3744b2) to `normalizedString`. Sorry for the inconvenience.

**Pull request merged**
