### PR TITLE
Add MATLAB-Simulink Cross check results (FMI 2.0)

### PR DESCRIPTION
**Pull request by Simulink-FMI**
Add MATLAB-Simulink Cross-check results (FMI 2.0); successfully tested FMUS (cs and me) from Dymola, CATIA and SimulationX

### CODE REVIEW

**Review by lochel — COMMENTED** [review]
Thanks for the contribution.

Please note, the uploaded results do not match the required folder structure (see [add-results](https://github.com/modelica/fmi-cross-check#add-results)). The tool id from [tools.csv](https://github.com/modelica/fmi-standard.org/blob/master/_data/tools.csv) contains a whitespace, whereas the tool id from the folder structure in this pull request contains a dash.

Please also note that 9 of the 39 tested FMUs were not compliant with the latest rules and will therefore not show up in the results. You must upload result for at least one more exporting tool in order to pass the cross-check and thus get the “green label” on the [tools page](https://fmi-standard.org/tools/).

**Comment by Simulink-FMI** [comment]
Thanks for the comments.  I have updated the folder structure and also added results for two exporting tools.  Just curious,  could I know which 9 files were not compliant with the latest rules?  it will help us better understand rules, thanks.

**Comment by lochel** [comment]
There is unfortunately no overview of the not compliant tests, but they are marked with a file called `notCompliantWithLatestRules`, e.g., [fmi-cross-check/fmus/2.0/cs/win64/SimulationX/4.0.4/Rectifier](https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/SimulationX/4.0.4/Rectifier).

**Review by lochel — APPROVED** [review]
LGTM 👍

**Pull request merged**
