### PR TITLE
Add MapleSim 2018 FMUs 1.0ME.

### PR DESCRIPTION
**Pull request by Maplesoft-fmigroup**

### CODE REVIEW

**Comment by t-sommer** [comment]
The *_cc.csv is not required any more. It saves a lot of space if you don't upload it.

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer Question: Should I delete the *_cc.csv from the MapleSim 2018 fmus commit?

**Comment by t-sommer** [comment]
No. Just for the future.

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  Ok, thanks for clarifying this. One more question: for 'results' (formerly CrossCheck_Results), only 2 files are required now (Model_Name_out.csv and ReadMe.txt, with optional passed/fail file). Is the CSV-Compare tool not needed anymore?

**Comment by t-sommer** [comment]
Only `*_out.csv` and `passed` are needed. `README.md` is optional and no `passed` means "failed".

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer Thanks again. Last question: Is the following (text in **bold**) still enforced:?

> FMU importing tools must report on importing for all Reference FMUs available for the supported FMI Variant and supported platforms provided on the SVN server (Note: not required to "pass" because of potential missing capabilities of the FMU) and **must successfully import at least 3 FMUs for at least one supported platform of at least 3 exporting tools**, and run for as long as the {FMUName}_ref.opt stated and supply a .csv of the solution they computed to receive and "Available" status.

**Comment by t-sommer** [comment]
Yes, no changes here

**Pull request merged**
