### PR TITLE
added results for AUTOSAR Builder 2019fd01

### PR DESCRIPTION
**Pull request by f-verani**
Please find results for FMU generated by AUTOSAR Builder 2019fd01.

Do you when page https://fmi-standard.org/tools/ will be updated ?

### CODE REVIEW

**Comment by flochocinco** [comment]
I would like to rename ASim into AUTOSAR Builder, how to do so ?

**Comment by t-sommer** [comment]
You can change it [here](https://github.com/modelica/fmi-standard.org/blob/master/CONTRIBUTING.md#updating-the-tools-list). But please use a name without spaces (e.g. AUTOSAR_Builder).

**Comment by flochocinco** [comment]
renamed folder

**Comment by f-verani** [comment]
Hello,
Close this Request, I will do it again in new request.

**Pull request closed without merging**
