### PR TITLE
Mark FMUs that are not compliant due to external dependencies

### PR DESCRIPTION
**Pull request by lochel**
This pull request marks those tests as not compliant that have external dependencies, see #122. 
I tested _only_ the targets win64 and linux64. There are probably similar issues on some of the other targets.

### CODE REVIEW

**Review by t-sommer — CHANGES_REQUESTED** [review]
The FMI Steering Committee decided to back-port https://github.com/modelica/fmi-standard/pull/1478 to FMI 2.0.3, which would make this PR obsolete. We can leave it open until the change has been merged.

**Comment by chrbertsch** [comment]
> The FMI Steering Committee decided to back-port modelica/fmi-standard#1478 to FMI 2.0.3, which would make this PR obsolete. We can leave it open until the change has been merged.

Strictly speaking the FMUs with external dependencies will only be "legal" when the file externalDependencies.{txt|html}  is present in the  documentation folder. Shall we ask the tool vendors to "retrofit" their submitted FMUs with the this file including a description of the dependencies?

**Comment by t-sommer** [comment]
> Shall we ask the tool vendors to "retrofit" their submitted FMUs with the this file including a description of the dependencies?

FMI 2.0 FMUs "should" have the file, so not need to change existing FMUs.

**Comment by t-sommer** [comment]
Closing as https://github.com/modelica/fmi-standard/pull/1488 has been merged.

**Comment by casella** [comment]
> > Shall we ask the tool vendors to "retrofit" their submitted FMUs with the this file including a description of the dependencies?
> 
> FMI 2.0 FMUs "should" have the file, so not need to change existing FMUs.

@t-sommer, @chrbertsch, @andreas-junghanns , I understand there are some [technical reasons](https://github.com/modelica/fmi-standard/pull/1488#issuecomment-885658581) (that are not further specified, so I don't know what they are) to not make this file required in FMI 2.0, hence the "should" in the 2.0.3 spec. I am of course fine with that.

I wonder if the pool of cross-check FMUs shouldn't avoid including instances that should include the file, but actually don't (pun intended). Isn't this pool meant to be the golden yardstick for all tools to confront with?

**Comment by andreas-junghanns** [comment]
The "golden yardstick" should be the Reference FMUs. The XC pool is for the cold, hard reality of our dirty world. And there it is quite ok to show shortcomings in some of the tools because documenting this is also important to users out there wondering about which versions of which tools produce what kind of compatibility issues.

**Comment by casella** [comment]
@andreas-junghanns, you still crave for oil and grease, don't you 😄

**Pull request closed without merging**
