### PR TITLE
Add ANSYS_CFX_2019.R2

### PR DESCRIPTION
**Pull request by RobinSteed**

### CODE REVIEW

**Comment by t-sommer** [comment]
@RobinSteed, can you fix the result file that exceeds the 1 MB limit?

> /home/circleci/repo/results/2.0/cs/win64/ANSYS_CFX/2019.R2/DS_FMU_Export_from_Simulink/2.3.0/TestModel1_sf/TestModel1_sf_out.csv is larger than 1 MB (1.1 MB)

**Comment by RobinSteed** [comment]
@t-sommer, I have updated the .csv to be under the 1 MB limit.

**Comment by t-sommer** [comment]
Did you forget to add the `passed` files?

**Comment by RobinSteed** [comment]
I didn't include these as I thought they were optional<https://github.com/modelica/fmi-cross-check#add-results>.

Do you need the passed/failed from our tests? I had thought the final comparison would be done independently.
________________________________

**Comment by t-sommer** [comment]
The `passed` file is used to calculate the status in the cross-check results.

**Comment by RobinSteed** [comment]
I’ll definitely add them in that case!

So the “optional” instruction only refers to the “rejected” file, not the entire line. Looking back now I see that you only run the local tests if there is a “passed” file.


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by t-sommer** [comment]
Also note that in order to get a green button in the tools list you need to successfully import at least 3 FMUs of at least 3 different vendors (=9) for each platform you claim to support.

**Pull request closed without merging**
