### PR TITLE
Added cross-check results for PragmaDev Studio v5.3

### PR DESCRIPTION
**Pull request by mbrumbulli**

### CODE REVIEW

**Comment by t-sommer** [comment]
Some result files exceed the 1 MB file size limit:

```
results/2.0/cs/win32/PragmaDev_Studio/5.3/DS_FMU_Export_from_Simulink/2.3.0/TestModel1_sf/TestModel1_sf_out.csv is larger than 1 MB (1.6 MB)

results/2.0/cs/win32/PragmaDev_Studio/5.3/FMIToolbox_MATLAB/2.3/Discontinuities/Discontinuities_out.csv is larger than 1 MB (2.4 MB)

results/2.0/cs/win32/PragmaDev_Studio/5.3/FMIToolbox_MATLAB/2.3/Continuous/Continuous_out.csv is larger than 1 MB (1.6 MB)

results/2.0/me/win32/PragmaDev_Studio/5.3/DS_FMU_Export_from_Simulink/2.3.0/TestModel1_sf/TestModel1_sf_out.csv is larger than 1 MB (1.6 MB)

results/2.0/me/win32/PragmaDev_Studio/5.3/FMIToolbox_MATLAB/2.3/Discontinuities/Discontinuities_out.csv is larger than 1 MB (2.4 MB)

results/2.0/me/win32/PragmaDev_Studio/5.3/FMIToolbox_MATLAB/2.3/Continuous/Continuous_out.csv is larger than 1 MB (1.6 MB)
```

**Comment by mbrumbulli** [comment]
Nowhere is stated that there is a 1MB size limit for results. Am I missing smth?

**Comment by t-sommer** [comment]
The new cross-check rules have been approved by the FMI Steering Committee but not published yet:

> A CSV file must not be larger than 1 Megabyte.

Sorry for the inconvenience.

**Comment by t-sommer** [comment]
Also note that you need to provide results for at least 3 FMUs from 3 different vendors for every supported platform in order to get a green button in the tools table.

**Comment by mbrumbulli** [comment]
I will try to reduce the size of the result files. About the 3-3 rule, I indeed am aware of that. However, I don't know how to achieve the green button if there is only one vendor for 2.0/me/linux32. On this subject, how is it possible that there are tools marked with green in the website for 2.0/me/linux32 and  2.0/cs/linux32 with FMUs from less than 3 vendors?

**Comment by t-sommer** [comment]
If you've found an error in the result collection process please open a separate issue.

**Comment by mbrumbulli** [comment]
I have reduced the file size <1MB and added more cross-check results.

**Pull request merged**
