### PR TITLE
Added FMUs and results of EcosimPro-PROOSIS for cosimulation

### PR DESCRIPTION
**Pull request by dieggar**
The FMUs generated and the importation results for cosimualtion with EcsoimPro and PROOSIS simulation tools have been added to the cross validation repository.

### CODE REVIEW

**Comment by t-sommer** [comment]
We can increase the size limit for FMUs in the next release of FMPy (see CATIA-Systems/FMPy#91). In the mean time you could [add a placeholder](https://github.com/modelica/fmi-cross-check/blob/master/FMI-CROSS-CHECK-RULES.md#914-files-to-submit) `*.nofmu` and upload results for 3 different tools yourself to get a "green button" now.

**Comment by dieggar** [comment]
We have added the *.nofmu fies as you suggested, but the pull request finishes with errors because the *.fmu files are not included.
We have added the *.nofmu files and readme files where we explain how to get the *.fmu files.
What is the procedure to follow in this case? 
We are now blocked again at this point.

Thank you very much.

#!/bin/bash -eo pipefail
. venv/bin/activate
python -m fmpy.cross_check.validate_vendor_repo ~/repo
python -m fmpy.cross_check.result_tables ~/repo ~/repo/fmi-standard.org/_data

#################################
3 problems found in /home/circleci/repo
Validated 1236 FMUs and 10017 results
#################################


Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/Rectifier/Rectifier.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/Rectifier/Rectifier.fmu'

Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/heatexchanger/heatexchanger.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/heatexchanger/heatexchanger.fmu'

Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/CirculationPumps/CirculationPumps.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/CirculationPumps/CirculationPumps.fmu'
Exited with code 3

**Comment by dieggar** [comment]
We have added the *.nofmu fies as you suggested, but the pull request finishes with errors because the *.fmu files are not included.
We have added the *.nofmu files and readme files where we explain how to get the *.fmu files.
What is the procedure to follow in this case?
We are now blocked again at this point.
Thank you very much.
#!/bin/bash -eo pipefail
. venv/bin/activate
python -m fmpy.cross_check.validate_vendor_repo ~/repo
python -m fmpy.cross_check.result_tables ~/repo ~/repo/fmi-standard.org/_data
#################################
3 problems found in /home/circleci/repo
Validated 1236 FMUs and 10017 results
#################################
Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/Rectifier/Rectifier.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/Rectifier/Rectifier.fmu'
Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/heatexchanger/heatexchanger.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/heatexchanger/heatexchanger.fmu'
Error in /home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/CirculationPumps/CirculationPumps.fmu. [Errno 2] No such file or directory: '/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/CirculationPumps/CirculationPumps.fmu'
Exited with code 3


De: Torsten Sommer [mailto:notifications@github.com]
Enviado el: lunes, 16 de septiembre de 2019 8:48
Para: modelica/fmi-cross-check <fmi-cross-check@noreply.github.com>
CC: Diego García Álvarez <dgalvarez@empre.es>; Author <author@noreply.github.com>
Asunto: Re: [modelica/fmi-cross-check] Added FMUs and results of EcosimPro-PROOSIS for cosimulation (#70)


We can increase the size limit for FMUs in the next release of FMPy (see CATIA-Systems/FMPy#91<https://github.com/CATIA-Systems/FMPy/issues/91>). In the mean time you could add a placeholder<https://github.com/modelica/fmi-cross-check/blob/master/FMI-CROSS-CHECK-RULES.md#914-files-to-submit> *.nofmu and upload results for 3 different tools yourself to get a "green button" now.

**Comment by t-sommer** [comment]
Seems like nobody ever used this "feature" 😬

**Comment by dieggar** [comment]
Ok!

hehe, but what can we do in this case?

**Comment by t-sommer** [comment]
We'll fix it in the next FMPy release.

**Comment by dieggar** [comment]
Ok, when will this release launch? Could you inform us when this release is performed? 

Best regards.

**Comment by t-sommer** [comment]
The limit is now 10 MB for the FMUs.

**Comment by dieggar** [comment]
I have tried to perform a pull request and I got this error again (All files are lower than 10 Mb):


#!/bin/bash -eo pipefail
. venv/bin/activate
python -m fmpy.cross_check.validate_vendor_repo ~/repo
python -m fmpy.cross_check.result_tables ~/repo ~/repo/fmi-standard.org/_data

#################################
3 problems found in /home/circleci/repo
Validated 1236 FMUs and 10017 results
#################################


/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/Rectifier/Rectifier.fmu is larger than 4 MB (8.24185 MB)

/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/heatexchanger/heatexchanger.fmu is larger than 4 MB (8.3315 MB)

/home/circleci/repo/fmus/2.0/cs/win64/EcosimPro-PROOSIS/6.0.2/CirculationPumps/CirculationPumps.fmu is larger than 4 MB (9.41687 MB)
Exited with code 3

**Comment by t-sommer** [comment]
Seems like CI is stuck with FMPy 0.2.10:

> Requirement already satisfied: fmpy==0.2.10 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (0.2.10)

I have to look into this...

**Comment by dieggar** [comment]
Ok,

please, let me know when we could repeat this process again in order to pass the cross-check process.

**Comment by dieggar** [comment]
Hi there,

How is this process? We would like to finish this process as soon as possible.

We also would like to know what is the process to follow to appear as planned in model exchange in the web page.

Thank you very much.

**Comment by dieggar** [comment]
Hi there,

We would like to finish this process. Is there any new about this process? Can we upload our fmus with sizes bigger than 4 Mb.

Thank you very much.

**Comment by dieggar** [comment]
Hello,

is there some news about the procedure to update FMUs whose size in greater than 4 Mb. We would like to appear in the FMI-FMU webpage as soon as possible.

We also are interested in appearing as planned in model exchange standard in the web page.

Thank very much for your attention.

Diego Garcia-Alvarez.

**Pull request merged**
