### PR TITLE
Add OMSimulator v2.1.1 (win64, linux64 and linux32)

### PR DESCRIPTION
**Pull request by AnHeuermann**
Adding win64, linux64 and linux32 results for [OMSimulator v2.1.1](https://github.com/OpenModelica/OMSimulator/tree/v2.1.1)..

The import of the FMUs was done inside Docker containers `anheuermann/ompython:wine-bionic`, `anheuermann/ompython:focal` and `anheuermann/ompython:bionic32`.

The results with warning and error logs as well as interactive plots are available as html for [win64 (Ubuntu Bionic + wine)](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/history/build-v2.1.0-3%202021-01-28/wine64/fmi-cross-check.html),  [linux32 (Ubuntu Bionic)](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/history/build-v2.1.0-3%202021-01-28/linux32-bionic/fmi-cross-check.html) and [linux64 (Ubuntu Focal)](https://libraries.openmodelica.org/fmi-crosschecking/OMSimulator/history/build-v2.1.0-3%202021-01-28/linux64-focal/fmi-cross-check.html).

### CODE REVIEW

**Comment by AnHeuermann** [comment]
I added the Windows results as well. We are using wine to run them from Linux.

**Review by t-sommer — CHANGES_REQUESTED** [review]
Please add the `passed` files for the FMUs you imported successfully.

**Comment by AnHeuermann** [comment]
I missed to run my validation function on the windows commit. Thanks for finding it. I have updated my commits and also deleted some stray csv files that should not be in this repo.

**Comment by AnHeuermann** [comment]
I did also run `validate_repo.py` as well and it reported 0 problems.

**Pull request merged**
